<?php

namespace App\Constants;

class Errors extends Holder
{
    const SECRET_IS_REQUIRED = 'SECRET_IS_REQUIRED';
    const ERROR_ISSUING_REFRESH_TOKEN = 'ERROR_ISSUING_REFRESH_TOKEN';
    const BACKUP_CODES_ALREADY_PRESENT = 'BACKUP_CODES_ALREADY_PRESENT';
    const VALIDATION_FAILED = 'VALIDATION_FAILED';
    const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    const RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS';
    const ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED';
    const REQUEST_FAILED = 'REQUEST_FAILED';
    const MULTI_FACTOR_ALREADY_ENABLED = 'MULTI_FACTOR_ALREADY_ENABLED';
    const MULTI_FACTOR_NOT_ENABLED = 'MULTI_FACTOR_NOT_ENABLED';
    const MULTI_FACTOR_PARAMETERS_MISSING = 'MULTI_FACTOR_PARAMETERS_MISSING';
    const MULTI_FACTOR_VERIFICATION_FAILED = 'MULTI_FACTOR_VERIFICATION_FAILED';
    const USER_VERIFICATION_FAILED = 'USER_VERIFICATION_FAILED';
    const USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED';
    const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    const EMAIL_VERIFICATION_NEEDED = 'EMAIL_VERIFICATION_NEEDED';
    const ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
    const AUTHENTICATION_NOT_ALLOWED = 'AUTHENTICATION_NOT_ALLOWED';
    const UNAUTHORIZED = 'UNAUTHORIZED';

    // Search
    const SEARCH_RESOURCE_MISMATCH = 'SEARCH_RESOURCE_MISMATCH';
    const SEARCH_ID_INVALID_OR_EXPIRED = 'SEARCH_ID_INVALID_OR_EXPIRED';

    // Pagination
    const REQUESTED_PAGE_DOES_NOT_EXIST = 'REQUESTED_PAGE_DOES_NOT_EXIST';

    // Node+Service related
    const COULD_NOT_ACCESS_NODE = 'COULD_NOT_ACCESS_NODE';
    const UNKNOWN_SERVICE = 'UNKNOWN_SERVICE';
    const UNKNOWN_ACTION = 'UNKNOWN_ACTION';
    const ACCESS_LEVEL_INSUFFICIENT = 'ACCESS_LEVEL_INSUFFICIENT';

    // Invoice+Billing related

    const BILLING_PROFILE_INCOMPLETE = 'BILLING_PROFILE_INCOMPLETE';
    const INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID';
    const INVOIDE_DUE_IS_LOWER_THAN_LOWEST_THRESHOLD = 'INVOIDE_DUE_IS_LOWER_THAN_LOWEST_THRESHOLD';

    // Validation
    const FIELD_REQUIRED = 'FIELD_REQUIRED';
    const FIELD_MAXLENGHT = 'FIELD_MAXLENGTH';
    const FIELD_MINLENGHT = 'FIELD_MINLENGTH';
}