<?php

namespace App\Constants;

class Errors {
  const SECRET_IS_REQUIRED = 'SECRET_IS_REQUIRED';  
  const ERROR_ISSUING_REFRESH_TOKEN = 'ERROR_ISSUING_REFRESH_TOKEN';
  const BACKUP_CODES_ALREADY_PRESENT = 'BACKUP_CODES_ALREADY_PRESENT';
}

