<?php

namespace App\Constants;

class Errors {
    const SECRET_IS_REQUIRED = 'SECRET_IS_REQUIRED';  
    const ERROR_ISSUING_REFRESH_TOKEN = 'ERROR_ISSUING_REFRESH_TOKEN';
    const BACKUP_CODES_ALREADY_PRESENT = 'BACKUP_CODES_ALREADY_PRESENT';
    const VALIDATION_FAILED = 'VALIDATION_FAILED';
    const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    const RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS';
    const ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED';
    const REQUEST_FAILED = 'REQUEST_FAILED';
    const TWO_FACTOR_ALREADY_ENABLED = 'TWO_FACTOR_ALREADY_ENABLED';
    const TWO_FACTOR_NOT_ENABLED = 'TWO_FACTOR_NOT_ENABLED';
    const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
}

