<?php


namespace App\Http\Controllers\V1;


use App\Node;
use App\Libraries\SearchManager;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class NodeController extends CRUDController
{
    public function __construct()
    {
        $this->resource = 'node';
    }

    public function index(Request $request) : JsonResponse
    {
        $this->authorizeResource();
        $rules = [
            'searchId' => 'sometimes|alphanum'
        ];
        $this->validate($request, $rules);

        if ($request->has('searchId'))
        {
            $searchId = $request->input('searchId');
            $results = SearchManager::process($searchId, 'node');
            return $this->respond($results->toArray());
        }

        return $this->respond(Node::all()->toArray());
    }

    public function store(Request $request): JsonResponse
    {
        $this->authorizeResource(Node::find(2), 'node.show');

        return parent::store($request); // TODO: Change the autogenerated stub
    }
}